django_test/flowerGuide/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from . import views

app_name = 'flowerGuide'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('flower/<slug:slug>/', views.detailView, name='detail'),
    path('flowerList', views.ListView.as_view(), name='list')
]

django_test/mytestsite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('flowerGuide/', include('flowerGuide.urls')),
    path('', views.index, name="index")
]

django_test/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

django_test/flowerGuide/models.py
import datetime

from autoslug import AutoSlugField
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify


class Flower(models.Model):
    name = models.CharField(max_length=100)
    species_name = models.CharField(max_length=300)
    family_name = models.CharField(max_length=300)
    description = models.TextField()
    slug = AutoSlugField(populate_from='name')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug': self.slug})

django_test/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django_test/flowerGuide/views.py
import os

from django.conf import settings
from django.shortcuts import get_object_or_404, render
from django.views import generic
from .models import Flower


class IndexView(generic.TemplateView):
    template_name = 'flowerGuide/index.html'


def detailView(request, slug):
    flower = get_object_or_404(Flower, slug=slug)
    path = settings.STATIC_ROOT
    img_list = []
    try:
        img_list = os.listdir(path + '\\images\\' + flower.slug)
    except FileNotFoundError:
        return render(request, 'flowerGuide/detail.html', {'flower': flower, 'images': img_list})
    else:
        for i, s in enumerate(img_list):
            img_list[i] = 'flowerGuide/images/' + flower.slug + '/' + s
        return render(request, 'flowerGuide/detail.html', {'flower': flower, 'images': img_list})


class ListView(generic.ListView):
    template_name = 'flowerGuide/list.html'
    context_object_name = 'flower_list'

    def get_queryset(self):
        return Flower.objects.order_by('id').all()

django_test/mytestsite/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect


def index(request):
    return HttpResponse("This is the Home Page")

django_test/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

django_test/flowerGuide/templates/flowerGuide/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta charset="utf-8">
    <title>Flower Guide</title>
    <meta content="" name="description">
    <meta content="" name="author">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    {% load static %}
    <link href="{% static 'flowerGuide/style.css' %}" rel="stylesheet" type="text/css">
    <!-- Load htmlshiv and Respond.js for IE 9+ support
         of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Specify the URI of your favicon in href attribute -->
    <link href="" rel="shortcut icon">

    <!-- The commented-out markup below is for iOS/Android bookmarking icons-->
    <!--
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="196x196" href="">
    <link rel="apple-touch-icon" sizes="152x152" href="">
    -->

    <!-- Reference non-render-blocking scripts here
         and use async attribute if possible
         Example: <script src="" async></script> -->
</head>
<body>
<div class="header">
    <h1>Flower Guide</h1>
</div>
<div class="row">
    <div class="col-2 navbar">
        <br>
        <ul>
            <li><a href="{% url 'flowerGuide:index' %}">Home</a></li>
            <li><a href="{% url 'flowerGuide:list' %}">Flower List</a></li>
        </ul>
    </div>
    <div class="col-7 main">
        <div class="content">
            <h1>{{ flower.name }}</h1>
            <p><b>Species Name:</b> {{ flower.species_name }}</p>
            <p><b>Family Name:</b> {{ flower.family_name }} </p>
            <p><b>Description:</b></p> {{ flower.description|linebreaks }}
            {% if images %}
            <p><b>Images</b></p>
            {% for image in images %}
            <div class="gallery">
                {% load static %}
                <a href="{% static image %}" target="_blank">
                    {% load static %}
                    <img alt="{{ image }}" src="{% static image %}">
                </a>
            </div>
            {% endfor %}
            {% else %}
            <p>No images available.</p>
            {% endif %}
        </div>
    </div>
</div>
<div class="footer">
    <p>The Flower Guide</p>
</div>
<!-- Put render-blocking scripts here if possible
     and use async attribute if possible -->
<!-- SCRIPTS -->
<!-- Example: <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> -->
<!-- NOTE: jQuery 2.x is used in the script reference example above, which doesn't support IE 8 and below. -->
</body>
</html>

django_test/flowerGuide/templates/flowerGuide/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta charset="utf-8">
    <title>Flower Guide</title>
    <meta content="" name="description">
    <meta content="" name="author">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    {% load static %}
    <link href="{% static 'flowerGuide/style.css' %}" rel="stylesheet" type="text/css">
    <!-- Load htmlshiv and Respond.js for IE 9+ support
         of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Specify the URI of your favicon in href attribute -->
    <link href="" rel="shortcut icon">

    <!-- The commented-out markup below is for iOS/Android bookmarking icons-->
    <!--
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="196x196" href="">
    <link rel="apple-touch-icon" sizes="152x152" href="">
    -->

    <!-- Reference non-render-blocking scripts here
         and use async attribute if possible
         Example: <script src="" async></script> -->
</head>
<body>
<div class="header">
    <h1>Flower Guide</h1>
</div>
<div class="row">
    <div class="col-2 navbar">
        <ul>
            <li><a href="{% url 'flowerGuide:index' %}">Home</a></li>
            <li><a href="{% url 'flowerGuide:list' %}">Flower List</a></li>
        </ul>
    </div>
    <div class="col-6 main">
        <div class="content">
            <h1>The Flower Guide</h1>
            <p>A database of flower information</p>
        </div>
    </div>
</div>
<!--<div class="footer">-->
<!--    <p>The Flower Guide</p>-->
<!--</div>-->
<!-- Put render-blocking scripts here if possible
     and use async attribute if possible -->
<!-- SCRIPTS -->
<!-- Example: <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> -->
<!-- NOTE: jQuery 2.x is used in the script reference example above, which doesn't support IE 8 and below. -->
</body>
</html>

django_test/flowerGuide/templates/flowerGuide/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta charset="utf-8">
    <title>Flower Guide</title>
    <meta content="" name="description">
    <meta content="" name="author">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    {% load static %}
    <link href="{% static 'flowerGuide/style.css' %}" rel="stylesheet" type="text/css">
    <!-- Load htmlshiv and Respond.js for IE 9+ support
         of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Specify the URI of your favicon in href attribute -->
    <link href="" rel="shortcut icon">

    <!-- The commented-out markup below is for iOS/Android bookmarking icons-->
    <!--
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="196x196" href="">
    <link rel="apple-touch-icon" sizes="152x152" href="">
    -->

    <!-- Reference non-render-blocking scripts here
         and use async attribute if possible
         Example: <script src="" async></script> -->
</head>
<body>
<div class="header">
    <h1>Flower Guide</h1>
</div>
<div class="row">
    <div class="col-2 navbar">
        <ul>
            <li><a href="{% url 'flowerGuide:index' %}">Home</a></li>
            <li><a href="{% url 'flowerGuide:list' %}">Flower List</a></li>
        </ul>
    </div>
    <div class="col-6 main">
        {% if flower_list %}
        <ul>
            {% for flower in flower_list %}
                <li><a href="{% url 'flowerGuide:detail' flower.slug %}">{{ flower.name }}</a></li>
            {% endfor %}
        </ul>
            {% else %}
        <p>Could not retrieve flowers</p>
        {% endif %}
    </div>
</div>
<!--<div class="footer">-->
<!--    <p>The Flower Guide</p>-->
<!--</div>-->
<!-- Put render-blocking scripts here if possible
     and use async attribute if possible -->
<!-- SCRIPTS -->
<!-- Example: <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> -->
<!-- NOTE: jQuery 2.x is used in the script reference example above, which doesn't support IE 8 and below. -->
</body>
</html>

django_test/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{ question.question_text }}</title></head>
    <body>
        <h1>{{ question.question_text }}</h1>
        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}</li>
            {% endfor %}
        </ul>
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Vote">
        </form>
    </body>
</html>

django_test/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
        {% else %}
    <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

django_test/polls/templates/polls/results.html
<!Doctype HTML>
<html>
    <head>
    </head>
    <body>
        <h1>{{ question.question_text }}</h1>
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
        </ul>

        <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    </body>
</html>